### ISSUE TITLE
Erweiterung beschreibender Icons in CX

### ISSUE THREAD

**Issue by BettySlobo** [bsi-software/bsi-cx-design-build#1]
Hallo Zusammen,

es gibt nicht genügend Icons in CX, die in der rechten Spalte in der Konfiguration die Content Elemente beschreiben, wie z.B. das Text Icon für Plain Text etc.

Ist geplant, dass zukünftig weitere beschreibende Icons zur Verfügung stehen für die Erstellung von Content Elementen z.B. Buttons etc.

Viele Grüße,
Bettina Slobodan

adesso SE
Streitfeldstraße 25
81673 München
bettina.slobodan@adesso.de

**Comment by innerjoin** [comment]
Hallo Bettina

Die Liste ist fix und kann nicht einfach so geändert werden. Dazu ist Stand heute eine Änderung im Produkt nötig. Wir verwenden m.W. die Streamline Icon Library. Du kannst uns gerne eine Liste der gewünschten Icons zustellen und wir werden diese für einen nächsten Release berücksichtigen:
https://app.streamlinehq.com/icons

Beste Grüsse
Lukas
