### ISSUE TITLE
Statische Assets per js ausliefern

### ISSUE THREAD

**Issue by mroettgen** [bsi-software/bsi-cx-design-build#2]
Hallo zusammen,

ich habe gerade folgenden Anwendungsfall und bin mir unsicher, wo es hakt:

In meinem JavaScript setze ich dynamisch das src-Attribut eines HTML <img>-Elements auf ein Bild, das relativ zum Content-Root unter `./static/images/my-icon.svg` liegt. Im `template.twig` würde ich das ja in `bsi_cx_asset()` wrappen, aber finde keine entsprechende JS-Methode.

Bin ich hier komplett auf dem Holzweg und es gibt eine einfachere Variante, statische Assets über das Design-Zip per js anzusteuern?

Beispiel:

```twig
<!-- ... -->
<img id="cool-dynamic-image" src=" {{ bsi_cx_asset('./static/placeholder.svg') }}"/>
<!-- ... -->
```

```js
// ...
// 👇 wäre der intuitive Gedanke, der leider nicht zum Ziel führt
document.querySelectorAll('#cool-dynamic-image').src = './static/show-on-button-click.svg'; 
// ...
```

Meine Hoffnung wäre, dass es irgendwo eine js-Entsprechung zu bsi_cx_asset('file-path') gibt, die ich nur noch nicht entdeckt habe

**Comment by ofabel** [comment]
Das JS äquivalent zum `bsi_cx_asset(path)` wäre `require(path)` resp. `import file from '...'` (in einem Modul). Dann hast du aber vermutlich das Problem, dass die `{{designBaseUrl}}` nicht aufgelöst wird. Darum würde ich das folgendermassen lösen:

````twig
<script>
  {% set images = {
    placeholder: bsi_cx_asset('./content-elements/content/title/placeholder.png')
  } %}
  window.images = {{ images|json_encode|raw }};
</script>
````

Nun hast du das globale Objekt `images` zur Verfügung, welches die Assets mit dem korrekten Pfad enthält.

Für welche CX Version entwickelst du? Und was für ein Template Typ (Landingpage, E-Mail, Website)? Die hier beschriebene Variante funktioniert grundsätzlich immer.

**Comment by mroettgen** [comment]
Ein Portal isses, wir sind aktuell auf Core 16.3.40 / CX 1.3.40 

Verstehe ich das richtig, dass ich damit alle Bilder, die ich so ansprechen möchte, händisch im besagten Objekt registrieren muss? Mir wäre natürlich lieber, wenn ich dynamisch unterwegs sein könnte.

`import/require` würde dafür sorgen, dass webpack das Bild mit einpackt und die `{{ designBaseUrl }}` löst den Anfang von dem Pfad auf, wo die gerenderte Seite im Browser hinterher das Bild herholt, richtig? Vielleicht kann ich mir ja was basteln, was die URL korrekt hinzaubert.

**Comment by ofabel** [comment]
Den Portal Typ gibt es nicht, ich vermute also mal Website oder Landingpage (`.withDesignType(DesignType.WEBSITE)` im `webpack.config.js`). Ich Frage, da CX 1.3 nur für Websites die `{{ designBaseUrl }}` kennt. Landingpages setzen einen `<base>` Tag im Header. Somit sollten die dynamisch generierten Pfade auf Landingpages automatisch korrekt aufgelöst werden, während bei Websites wohl ein Umweg über das `window.location` Objekt gemacht werden muss.

Dynamische Imports sind immer etwas problematisch, da diese beim Erstellen des Bundles nicht aufgelöst werden können und die gewünschten Assets so evtl. nicht im Bundle landen. Du könntest aber die Bilder in den `<template-root>/assets` [Ordner](https://github.com/bsi-software/bsi-cx-design-build/wiki/First-Steps#assets) ablegen, die dort platzierten Dateien landen _immer_ im Bundle, egal ob referenziert oder nicht. Die Dateien und Ordner aus `/assets/**/*` werden auch nicht umbenannt.

**Comment by mroettgen** [comment]
Ah, ja richtig - der `DesignType.WEBSITE` isses! Danke, wieder was gelernt 👍  

Ich schau Montag auch mal durch die Docs, irgendwie hat mein kaffeedurchtränktes Hirn bisher die Sidebar im Wiki ignoriert...

Tatsächlich wäre meine Idee zum Hinzaubern der URL in die Richtung gegangen, CX dazu zu bringen, die designBaseUrl z. B. in den Header zu setzen. Ein Kollege hatte so etwas ähnliches schon für die Story Base URL gebaut. Der Hinweis mit dem assets Ordner ist auch super - an die Dateien komme ich aber trotzdem nicht ohne designBaseUrl ran, oder?

**Comment by ofabel** [comment]
Ja, da es sich um eine Website handelt benötigst du die `designBaseUrl`. Das Vorgehen klingt gut, du solltest einfach einen Meta Tag im Head platzieren können:

````handlebars
<meta name="design-base-url" content="{{designBaseUrl}}"/>
````

**Comment by mroettgen** [comment]
Sorry, wenn ich hier im geschlossenen Ticket nochmal poste aber... Der `assets` macht bei mir nicht das, was du beschreibst:

Zum Setup
```
templates/
- portal-website/
-- design.js
-- static/
...
-- assets/
--- image.svg
webpack.config.js
package.json
```

Abschnitt der Webpack-Config für das Template:
```
new BuildConfig()
    .withName('portal-website')
    .withVersion('1.0.0')
    .withTargetVersion(Version.CX_1_3)
    .withDesignType(DesignType.WEBSITE)
    .withRootPath(path.resolve(__dirname, 'templates', 'portal-website'))
    .withSourceMapEnabled(true)
    .withPropertiesFilePath(path.resolve(__dirname, 'properties.js'))
    .withModules(new ModuleConfig().withPath('main/main.js').withName('main'))
```
Probehalber hatte ich mal mittels `.withCopyAssetsFolderPath()` versucht, das hat mich allerdings auch nicht weitergebracht.

Struktur unter `/dist` schaut immer so aus:
```
email
landingpage
portal-website
- assets
-- assets
--- image.svg
- content-elements
- static
```

Struktur, die der Browser identifiziert:
![image](https://user-images.githubusercontent.com/14258552/167614288-5c655349-a00c-4eca-b11c-c9ab5cecb1e5.png)

Da sehe ich nirgends meine Assets. Ist hier etwas fehlkonfiguriert? Bilder, die über ein image-Element-Part reinkommen, landen unter `{{ resourceBaseUrl }}/andere-uuid-als-in-designBaseUrl/image.svg`

**Comment by ofabel** [comment]
Zum einen kannst du den Build auf Verison 1.8.1 aktualisieren, dann wird er nicht doppelt verschachtelt (`assets/assets/image.svg`). Wenn die Assets im `dist` Ordner und somit auch im ZIP landen werden sie beim Aktualisieren des Designs auch hochgeladen und am selben Ort abgelegt wie die anderen statischen Ressourcen. CX kennt nur eine Wahrheit und das ist der Inhalt der ZIP Datei. Nur was da drin hochgeladen wird landet auch auf dem Server. Bilder, welche über den image Element Part reinkommen, werden korrekt unter einer anderen UUID auf dem Resourceserver abgelegt (da auch für andere Inhalte über die Mediathek verfügbar).
