### ISSUE TITLE
Change default port

### ISSUE THREAD

**Issue by innerjoin** [bsi-software/bsi-cx-design-build#3]
The current default port is 9000. This is a widely used port in many organisations.  In our organisation, the majority of developers have this port already blocked by a running portainer instance.

I would suggest to use another one, e.g. 9001.

An alternative option would be to set the default value in all templates

**Comment by ofabel** [comment]
Good point! Checkout version [1.9.8](https://github.com/bsi-software/bsi-cx-design-build/releases/tag/1.9.8): I adjusted the default port to `auto` (according to the [webpack documentation](https://webpack.js.org/configuration/dev-server/#devserverport)).
