### ISSUE TITLE
Preview Image Location is not clear

### ISSUE THREAD

**Issue by dreamy-dev** [bsi-software/bsi-cx-design-build#4]
At the moment, the documentation is not clear enough on where the preview image should be located. No matter whether I put it into the root of the landingpage folder or the assets (static) folder, it results in an error message that the preview image can't be found. It'd be great if that could be further specified.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/49187442/211320602-9ae340d0-4eb9-4845-8de7-051d0bd6541b.png">

**Comment by ofabel** [comment]
How did you reference the preview image in the `design.js` file ? You have to use `require()` - otherwise Webpack will not bundle the file. You can also check if the file appears inside the ZIP file.

```javascript
// design.js

const {cx, Locale} = require('@bsi-cx/design-build');

module.exports = cx.design
  // ...
  .withPreviewImage(require('./preview.png'))
  // ...
```

The build won't fail if you don't use `require()`. If you use `require()` and the path is wrong, the build will fail.

**Comment by dreamy-dev** [comment]
I'm using `require()` and the build does not fail.

If I have the preview.png on the same level as the `design.js`, I don't get a build error and the generated ZIP does contain the preview image with a hash:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/49187442/211496969-74f318d6-3da3-4e1e-8702-2eade5e7121e.png">

But when I try to upload the ZIP, I'm still getting the same error message:
![image](https://user-images.githubusercontent.com/49187442/211497239-6911047e-2f6e-4b1e-825b-b19e367fe86e.png)

Oddly enough, even if I try to change the path in the `design.js` and put the preview.png into the assets folder, the build doesn't fail but I'm still getting the same error message when trying to upload it.

By looking at the issue closer together with Samuel Keusch, we found out that the BSI CX  design validation checks the path 1:1 without parsing the prefix `./`. 

We now figured out a workaround by adding this to the `webpack.config.js`:

```javascript

module.exports = WebpackConfigBuilder.fromConfigs(
    new BuildConfig()
// ...
.withAdditionalFilesToCopy(
            {
                from: path.resolve(
                    __dirname,
                    'templates',
                    'landingpage',
                    'preview.png'
                ),
                to: 'static/preview.png',
            }
        )
// ...
```

and changing the path in the design.js to the following:

```javascript

module.exports = cx.design
    // ....
    .withPreviewImage('static/preview.png')
```

Altough this workaround works, I'd still like to figure out how it's supposed to work according to the documentation.

**Comment by ofabel** [comment]
Thanks for the response and the investigation. What CX version is this? This is obviously a bug in BSI CX. I will issue a bug report and check if a can place a hint somewhere in the [troubleshooting](https://github.com/bsi-software/bsi-cx-design-build/wiki/Troubleshooting) chapter.

**Comment by dreamy-dev** [comment]
Thanks to you for your quick replies :) 
I have tested it on BSI CX Version 22.0.18.

**Comment by dreamy-dev** [comment]
Hi @ofabel do you have an update on this? I don't think it's integrated in the newest design version, is that correct?

**Comment by marleenjattke** [comment]
Hi @dreamy-dev Thanks for reporting this issue!
I added a new section to our [troubleshooting chapter](https://github.com/bsi-software/bsi-cx-design-build/wiki/Troubleshooting#preview-image). As soon as the bug is fixed in BSI CX, this will be reported here.

**Comment by marleenjattke** [comment]
With the latest build BSI Customer Suite 22.0.50 the issue was solved.
